#!bin/sh

csgo_pid=$(pidof csgo_linux64)

input="$(
    sudo gdb -n -q batch \
    -ex "attach $csgo_pid" \
    -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
    -ex "call \$dlopen(\"$(pwd)/bhop.so\" 1)" \
    -ex "detach" \
    -ex "quit"
)